"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0ViTQcl-eAM4WGt6vKql3a3KKXvNri6

## Mount to Colab runtime
"""

from google.colab import drive
import sys
if('google.colab' in sys.modules):
  print("Google drive detected, mounting...")
  drive.mount('/content/gdrive')
else:
  print("No Google drive found, ignoring...")
print("Done checking")

"""## Installing dependencies"""

# Commented out IPython magic to ensure Python compatibility.
# print("Installing program...")
# if 'google.colab' in sys.modules:
#   !pip install numpy pandas matplotlib seaborn scikit-learn tensorflow keras torch opencv-python labelme statsmodels scipy missingno
# else:
#   %pip install -r studio2.req.txt

"""## Import dependencies"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from scipy import interpolate

import os
import warnings

"""## Define Config"""

warnings.filterwarnings('ignore')

pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.7f}'.format

"""## 1. Data Collection

### Define columns, file to read and what class should be used for that file
- Since my student ID ends with 2, thus I will be doing Right Upper Arm (x,y,z) and Left Upper Arm (x,y,z)
- Boning dataset will have a class of '0'
- Slicing dataset will have a class of '1'
- There will also be a 'Frame' column as well
"""

os.chdir("/content/gdrive/MyDrive") if 'google.colab' in sys.modules else None
BASE_PATH = os.getcwd() + "/Colab Notebooks/COS40007/Assignment 2/ampc2" if 'google.colab' in sys.modules else os.getcwd() + "/ampc2"
contents_to_read = {
    'boning': {
        'fName': BASE_PATH + '/Boning.csv',
        'class': 0
    },
    'slicing': {
        'fName': BASE_PATH + '/Slicing.csv',
        'class': 1
    }
}
columns_to_read = [f'Right Upper Arm {k}' for k in ['x', 'y', 'z']] + [f'Left Upper Arm {k}' for k in ['x', 'y', 'z']] + ['Frame']

"""### Read the dataset with chosen columns, append the 'class' feature to the file"""

boning_raw_df = pd.read_csv(contents_to_read['boning']['fName'], usecols=columns_to_read)
boning_df = boning_raw_df.copy()
boning_df['class'] = contents_to_read['boning']['class']
slicing_raw_df = pd.read_csv(contents_to_read['slicing']['fName'], usecols=columns_to_read)
slicing_df = slicing_raw_df.copy()
slicing_df['class'] = contents_to_read['slicing']['class']
print(f"Shape of boning: {boning_df.shape}")
print(f"Shape of slicing: {slicing_df.shape}")

"""### Concat two datasets to be one and save it as combined_data.csv"""

concatenated_df = pd.concat([boning_df, slicing_df], ignore_index=True)
concatenated_df.to_csv(BASE_PATH + "/combined_data.csv", index=False)
concatenated_df.info()

"""## 2. Create Composite Columns

### Read the previously saved dataset
"""

concatenated_raw_df = pd.read_csv(BASE_PATH + "/combined_data.csv")
concatenated_df = concatenated_raw_df.copy()
concatenated_df.info()

concatenated_df.head()

"""### Utils function for calculating Root mean square value, Roll and Pitch"""

def calc_rmsq_for_cols(df: pd.DataFrame, cols: list[str]):
  return np.sqrt(np.mean(df[cols] ** 2, axis=1))

def calc_roll_for_col(df: pd.DataFrame, col: str):
  return 180 * np.arctan2(df[f'{col} y'], np.sqrt(df[f'{col} x'] ** 2 + df[f'{col} z'] ** 2)) / np.pi

def calc_pitch_for_col(df: pd.DataFrame, col: str):
  return 180 * np.arctan2(df[f'{col} x'], np.sqrt(df[f'{col} y'] ** 2 + df[f'{col} z'] ** 2)) / np.pi

"""### Calculate required composite data for Right Hand features


"""

concatenated_df['right_upper_xy_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Right Upper Arm x', 'Right Upper Arm y'])
concatenated_df['right_upper_yz_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Right Upper Arm y', 'Right Upper Arm z'])
concatenated_df['right_upper_xz_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Right Upper Arm x', 'Right Upper Arm z'])
concatenated_df['right_upper_xyz_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Right Upper Arm x', 'Right Upper Arm y', 'Right Upper Arm z'])

concatenated_df['right_upper_roll'] = calc_roll_for_col(concatenated_df, 'Right Upper Arm')
concatenated_df['right_upper_pitch'] = calc_pitch_for_col(concatenated_df, 'Right Upper Arm')

"""### Calculate required composite data for Left Hand features"""

concatenated_df['left_upper_xy_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Left Upper Arm x', 'Left Upper Arm y'])
concatenated_df['left_upper_yz_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Left Upper Arm y', 'Left Upper Arm z'])
concatenated_df['left_upper_xz_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Left Upper Arm x', 'Left Upper Arm z'])
concatenated_df['left_upper_xyz_rmsq'] = calc_rmsq_for_cols(concatenated_df, ['Left Upper Arm x', 'Left Upper Arm y', 'Left Upper Arm z'])

concatenated_df['left_upper_roll'] = calc_roll_for_col(concatenated_df, 'Left Upper Arm')
concatenated_df['left_upper_pitch'] = calc_pitch_for_col(concatenated_df, 'Left Upper Arm')

concatenated_df.info()

"""### Save it as "composited_data.csv"
"""

concatenated_df.to_csv(BASE_PATH + "/composited_data.csv", index=False)
concatenated_df.head()