"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0ViTQcl-eAM4WGt6vKql3a3KKXvNri6

## Mount to Colab runtime
"""

from google.colab import drive
import sys
if('google.colab' in sys.modules):
  print("Google drive detected, mounting...")
  drive.mount('/content/gdrive')
else:
  print("No Google drive found, ignoring...")
print("Done checking")

"""## Installing dependencies"""

# Commented out IPython magic to ensure Python compatibility.
# print("Installing program...")
# if 'google.colab' in sys.modules:
#   !pip install numpy pandas matplotlib seaborn scikit-learn tensorflow keras torch opencv-python labelme statsmodels scipy missingno
# else:
#   %pip install -r studio2.req.txt

"""## Import dependencies"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import find_peaks
from scipy import interpolate

import os
import warnings

"""## Define Config"""

warnings.filterwarnings('ignore')

pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.7f}'.format